[package]
name = "helpergit"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.20.4"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
chrono = "0.4"
crossterm = "0.29"
ratatui = "0.30.0"

[[bin]]
name = "hg"
path = "src/main.rs"
